arteries:
- id: inferior_gluteal_artery
  name: Inferior Gluteal Artery
  branches_from: internal_iliac_artery
  supplies:
  - levator_ani_pubococcygeus_head
  - levator_ani_iliococcygeus_head
  - coccygeus_head
- id: internal_pudendal_artery
  name: Internal Pudendal Artery
  branches_from: internal_iliac_artery
  supplies:
  - levator_ani_pubococcygeus_head
  - levator_ani_iliococcygeus_head
  - levator_ani_puborectalis_head
  - deep_transverse_perineal_head
  - external_urethral_sphincter_head
- id: obturator_artery
  name: Obturator Artery
  branches_from: internal_iliac_artery
  supplies:
  - deep_transverse_perineal_head
