[tool.poetry]
name = "stronger"
version = "0.1.0"
description = ""
authors = ["Tom <tomrfreeman3@gmail.com>"]
readme = "README.md"
packages = [{include = "stronger"}]

[tool.poetry.dependencies]
python = "^3.12"
pyyaml = "^6.0.3"
neo4j = "^6.0.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
