[tool.poetry]
name = "anatomy-graphdb"
version = "1.0.1"
description = "Canonical anatomy domain dataset and Neo4j graph builder."
license = "MIT"
authors = ["Tom <tomrfreeman3@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/Freehily/stronger-domain-graphdb"
repository = "https://github.com/Freehily/stronger-domain-graphdb"
documentation = "https://github.com/Freehily/stronger-domain-graphdb#readme"
keywords = ["anatomy", "neo4j", "graphdb", "fitness", "domain-model"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Medical Science Apps.",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [{include = "anatomy_graphdb"}]
include = [
  {path = "config/**/*.yaml", format = ["sdist", "wheel"]},
  {path = "anatomy_graphdb/assets/**", format = ["sdist", "wheel"]},
]

[tool.poetry.dependencies]
python = "^3.12"
pyyaml = "^6.0.3"
neo4j = {version = "^6.0.2", optional = true}

[tool.poetry.extras]
neo4j = ["neo4j"]

[tool.poetry.urls]
Changelog = "https://github.com/Freehily/stronger-domain-graphdb/blob/main/CHANGELOG.md"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.4.1"

[tool.poetry.scripts]
anatomy-graphdb = "anatomy_graphdb.cli.anatomy:main"
stronger-anatomy = "anatomy_graphdb.cli.anatomy:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
