bones:
- id: pelvis
  name: Pelvis
  region: Pelvic Girdle
  attachments:
  - anterior_superior_iliac_spine
- id: fascia
  name: Abdominal Fascia
  region: Connective Tissue
  attachments: []
- id: sacrum
  name: Sacrum
  region: Pelvis
  attachments: []
- id: calcaneus
  name: Calcaneus
  region: Foot
  attachments:
  - calcaneal_tuberosity_medial_process
  - calcaneal_tuberosity_lateral_process
- id: metatarsal_1
  name: 1st Metatarsal
  region: Foot
  attachments:
  - medial_tubercle_1st_metatarsal
  - base_1st_metatarsal
- id: metatarsal_5
  name: 5th Metatarsal
  region: Foot
  attachments:
  - base_5th_metatarsal
- id: proximal_phalanx_hallux
  name: Proximal Phalanx of Hallux
  region: Foot
  attachments:
  - medial_tubercle_proximal_phalanx_hallux
- id: phalanges_proximal
  name: Proximal Phalanges 2-5
  region: Foot
  attachments:
  - proximal_phalanges_2_5_medial
  - proximal_phalanges_3_5_lateral
- id: phalanges_middle
  name: Middle Phalanges 2-5
  region: Foot
  attachments:
  - middle_phalanges_2_5
- id: tendons
  name: Tendons
  region: Foot
  attachments:
  - tendons_flexor_digitorum_longus_2_5
  - tendons_flexor_digitorum_longus_digital_slips
- id: extensor_expansion
  name: Extensor Expansion (Digits 2-5)
  region: Foot
  attachments:
  - extensor_expansion_toe2
  - extensor_expansion_toe3
  - extensor_expansion_toe4
  - extensor_expansion_toe5
- id: metatarsals
  name: Metatarsals 2-4
  region: Foot
  attachments:
  - metatarsal_heads_2_5
- id: femur
  name: Femur
  region: Thigh
  attachments:
  - greater_trochanter
  - gluteal_tuberosity
  - anterior_femoral_shaft
  - pectineal_line_femur
  - linea_aspera
  - medial_femoral_condyle
  - lateral_femoral_condyle
  - adductor_tubercle
- id: patella
  name: Patella
  region: Knee
  attachments:
  - base_of_patella
- id: tibia
  name: Tibia
  region: Leg
  attachments:
  - medial_tibial_condyle
  - lateral_tibial_condyle
  - tibial_tuberosity
  - pes_anserinus
  - tibial_shaft_medial
  - soleal_line
- id: fibula
  name: Fibula
  region: Leg
  attachments:
  - head_of_fibula
  - fibular_shaft
- id: foot
  name: Foot Bones
  region: Foot
  attachments:
  - navicular_tuberosity
  - medial_cuneiform
  - intermediate_cuneiform
  - lateral_cuneiform
  - base_1st_metatarsal
  - base_5th_metatarsal
  - metatarsal_heads_2_5
  - proximal_phalanges_2_5_plantar
  - distal_phalanx_hallux
