arteries:
- id: superior_gluteal_artery
  name: Superior Gluteal Artery
  branches_from: internal_iliac_artery
  supplies:
  - gluteus_medius_head
  - gluteus_minimus_head
  - tensor_fasciae_latae_head
  - piriformis_head
- id: inferior_gluteal_artery
  name: Inferior Gluteal Artery
  branches_from: internal_iliac_artery
  supplies:
  - gluteus_maximus_head
- id: obturator_artery
  name: Obturator Artery
  branches_from: internal_iliac_artery
  supplies:
  - pectineus_head
  - gracilis_head
- id: femoral_artery
  name: Femoral Artery
  branches_from: external_iliac_artery
  supplies:
  - rectus_femoris_head
  - vastus_medialis_head
  - vastus_intermedius_head
  - sartorius_head
- id: deep_femoral_artery
  name: Deep Femoral Artery
  branches_from: femoral_artery
  supplies:
  - adductor_longus_head
  - adductor_brevis_head
  - adductor_magnus_adductor_head
  - adductor_magnus_hamstring_head
  - biceps_femoris_long_head
  - biceps_femoris_short_head
  - semitendinosus_head
  - semimembranosus_head
- id: lateral_circumflex_femoral_artery
  name: Lateral Circumflex Femoral Artery
  branches_from: deep_femoral_artery
  supplies:
  - tensor_fasciae_latae_head
  - rectus_femoris_head
  - vastus_lateralis_head
- id: popliteal_artery
  name: Popliteal Artery
  branches_from: femoral_artery
  supplies:
  - plantaris_head
- id: anterior_tibial_artery
  name: Anterior Tibial Artery
  branches_from: popliteal_artery
  supplies:
  - tibialis_anterior_head
  - extensor_digitorum_longus_head
  - extensor_hallucis_longus_head
- id: fibular_artery
  name: Fibular (Peroneal) Artery
  branches_from: posterior_tibial_artery
  supplies:
  - fibularis_longus_head
  - fibularis_brevis_head
