muscle_groups:
  entries:
    - slug: abs
      name: Abs
    - slug: obliques
      name: Obliques
    - slug: biceps
      name: Biceps
    - slug: forearms
      name: Forearms
    - slug: triceps
      name: Triceps
    - slug: calves
      name: Calves
    - slug: glutes
      name: Glutes
    - slug: hamstrings
      name: Hamstrings
    - slug: lower_back
      name: Lower Back
    - slug: quads
      name: Quads
    - slug: chest
      name: Chest
    - slug: lats
      name: Lats
    - slug: shoulders
      name: Shoulders
    - slug: upper_back
      name: Upper Back
    - slug: adductors
      name: Adductors