- slug: abductor_digiti_minimi
  name: Abductor Digiti Minimi
  group_slug: calves

- slug: abductor_hallucis
  name: Abductor Hallucis
  group_slug: calves

- slug: abductor_pollicis_longus
  name: Abductor Pollicis Longus
  group_slug: forearms

- slug: abductor_pollicis_brevis
  name: Abductor Pollicis Brevis
  group_slug: forearms

- slug: adductor_brevis
  name: Adductor Brevis
  group_slug: adductors

- slug: adductor_group
  name: Hip Adductor Functional Group
  group_slug: adductors

- slug: adductor_longus
  name: Adductor Longus
  group_slug: adductors
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/adductor_longus.svg

- slug: adductor_magnus
  name: Adductor Magnus
  group_slug: adductors
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/adductor_magnus.svg

- slug: adductor_pollicis
  name: Adductor Pollicis
  group_slug: forearms

- slug: anconeus
  name: Anconeus
  group_slug: triceps

- slug: biceps_brachii
  name: Biceps Brachii
  group_slug: biceps
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/biceps_brachii.svg

- slug: biceps_femoris
  name: Biceps Femoris
  group_slug: hamstrings
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/biceps_femoris.svg

- slug: brachialis
  name: Brachialis
  group_slug: biceps
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/brachialis.svg

- slug: brachioradialis
  name: Brachioradialis
  group_slug: biceps
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/brachioradialis.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/brachioradialis.svg

- slug: coracobrachialis
  name: Coracobrachialis
  group_slug: biceps

- slug: deltoid
  name: Deltoid
  group_slug: shoulders
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/deltoid.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/deltoid.svg

- slug: dorsiflexor_group
  name: Dorsiflexor Functional Group
  group_slug: calves

- slug: erector_spinae_iliocostalis
  name: Iliocostalis
  group_slug: spinal_erectors

- slug: erector_spinae_longissimus
  name: Longissimus
  group_slug: spinal_erectors

- slug: erector_spinae_spinalis
  name: Spinalis
  group_slug: spinal_erectors

- slug: extensor_carpi_radialis_brevis
  name: Extensor Carpi Radialis Brevis
  group_slug: forearms

- slug: extensor_carpi_radialis_longus
  name: Extensor Carpi Radialis Longus
  group_slug: forearms
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/extensor_carpi_radialis_longus.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/extensor_carpi_radialis_longus.svg

- slug: extensor_carpi_ulnaris
  name: Extensor Carpi Ulnaris
  group_slug: forearms

- slug: extensor_digiti_minimi
  name: Extensor Digiti Minimi
  group_slug: forearms

- slug: extensor_digitorum
  name: Extensor Digitorum
  group_slug: forearms

- slug: extensor_digitorum_longus
  name: Extensor Digitorum Longus
  group_slug: calves

- slug: extensor_hallucis_longus
  name: Extensor Hallucis Longus
  group_slug: calves

- slug: extensor_indicis
  name: Extensor Indicis
  group_slug: forearms

- slug: extensor_pollicis_brevis
  name: Extensor Pollicis Brevis
  group_slug: forearms

- slug: extensor_pollicis_longus
  name: Extensor Pollicis Longus
  group_slug: forearms

- slug: external_oblique
  name: External Oblique
  group_slug: obliques
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/external_oblique.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/external_oblique.svg

- slug: fibularis_brevis
  name: Fibularis Brevis
  group_slug: calves

- slug: fibularis_longus
  name: Fibularis Longus
  group_slug: calves
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/fibularis_longus.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/fibularis_longus.svg

- slug: flexor_carpi_radialis
  name: Flexor Carpi Radialis
  group_slug: forearms
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/flexor_carpi_radialis.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/flexor_carpi_radialis.svg

- slug: flexor_carpi_ulnaris
  name: Flexor Carpi Ulnaris
  group_slug: forearms
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/flexor_carpi_ulnaris.svg

- slug: flexor_digitorum_brevis
  name: Flexor Digitorum Brevis
  group_slug: calves

- slug: flexor_digitorum_longus
  name: Flexor Digitorum Longus
  group_slug: calves

- slug: flexor_digitorum_profundus
  name: Flexor Digitorum Profundus
  group_slug: forearms

- slug: flexor_digitorum_superficialis
  name: Flexor Digitorum Superficialis
  group_slug: forearms

- slug: flexor_digiti_minimi_brevis
  name: Flexor Digiti Minimi Brevis
  group_slug: forearms

- slug: flexor_hallucis_longus
  name: Flexor Hallucis Longus
  group_slug: calves

- slug: flexor_pollicis_brevis
  name: Flexor Pollicis Brevis
  group_slug: forearms

- slug: flexor_pollicis_longus
  name: Flexor Pollicis Longus
  group_slug: forearms

- slug: gastrocnemius
  name: Gastrocnemius
  group_slug: calves
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/gastrocnemius.svg

- slug: gastrocnemius_lateral_head
  name: Gastrocnemius (Lateral Head)
  group_slug: calves
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/gastrocnemius_lateral_head.svg

- slug: gastrocnemius_medial_head
  name: Gastrocnemius (Medial Head)
  group_slug: calves
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/gastrocnemius_medial_head.svg

- slug: gluteus_maximus
  name: Gluteus Maximus
  group_slug: glutes
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/gluteus_maximus.svg

- slug: gluteus_medius
  name: Gluteus Medius
  group_slug: glutes
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/gluteus_medius.svg

- slug: gluteus_minimus
  name: Gluteus Minimus
  group_slug: glutes

- slug: gracilis
  name: Gracilis
  group_slug: adductors
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/gracilis.svg

- slug: hamstring_group
  name: Hamstring Functional Group
  group_slug: hamstrings

- slug: hip_flexor_group
  name: Hip Flexor Functional Group
  group_slug: hip_flexors

- slug: hip_medial_rotators
  name: Hip Medial Rotators
  group_slug: adductors

- slug: iliotibial_band_muscles
  name: Iliotibial Band Muscles (Functional Group)
  group_slug: abductors

- slug: infraspinatus
  name: Infraspinatus
  group_slug: shoulders
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/infraspinatus.svg

- slug: internal_oblique
  name: Internal Oblique
  group_slug: obliques

- slug: latissimus_dorsi
  name: Latissimus Dorsi
  group_slug: lats
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/latissimus_dorsi.svg

- slug: levator_scapulae
  name: Levator Scapulae
  group_slug: upper_back

- slug: lumbrical_1
  name: Lumbrical 1
  group_slug: calves

- slug: lumbricals_2_4
  name: Lumbricals 2-4
  group_slug: calves

- slug: multifidus
  name: Multifidus
  group_slug: spinal_erectors

- slug: omohyoid
  name: Omohyoid
  group_slug: shoulders
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/omohyoid.svg

- slug: palmaris_longus
  name: Palmaris Longus
  group_slug: forearms

- slug: pectineus
  name: Pectineus
  group_slug: adductors
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/pectineus.svg

- slug: pectoralis_major
  name: Pectoralis Major
  group_slug: chest
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/pectoralis_major.svg

- slug: piriformis
  name: Piriformis
  group_slug: glutes

- slug: plantaris
  name: Plantaris
  group_slug: calves

- slug: pronator_quadratus
  name: Pronator Quadratus
  group_slug: forearms

- slug: pronator_teres
  name: Pronator Teres
  group_slug: forearms

- slug: quadratus_plantae
  name: Quadratus Plantae
  group_slug: calves

- slug: quadriceps_group
  name: Quadriceps Functional Group
  group_slug: quads

- slug: rectus_abdominis
  name: Rectus Abdominis
  group_slug: abs
  overlays:
    - view: front
      variant: "full"
      path: svgs/front/muscles/rectus_abdominis_full.svg
    - view: front
      variant: "lower"
      path: svgs/front/muscles/rectus_abdominis_lower.svg

- slug: rectus_femoris
  name: Rectus Femoris
  group_slug: quads
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/rectus_femoris.svg

- slug: rhomboid_major
  name: Rhomboid Major
  group_slug: upper_back
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/rhomboid_major.svg

- slug: rhomboid_minor
  name: Rhomboid Minor
  group_slug: upper_back

- slug: rotator_cuff
  name: Rotator Cuff Group
  group_slug: shoulders

- slug: sartorius
  name: Sartorius
  group_slug: hip_flexors
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/sartorius.svg

- slug: semimembranosus
  name: Semimembranosus
  group_slug: hamstrings

- slug: semispinalis_capitis
  name: Semispinalis Capitis
  group_slug: spinal_erectors

- slug: semispinalis_cervicis
  name: Semispinalis Cervicis
  group_slug: spinal_erectors

- slug: semitendinosus
  name: Semitendinosus
  group_slug: hamstrings
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/semitendinosus.svg

- slug: serratus_anterior
  name: Serratus Anterior
  group_slug: shoulders
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/serratus_anterior.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/serratus_anterior.svg

- slug: serratus_posterior_inferior_back
  name: Serratus Posterior Inferior
  group_slug: spinal_erectors

- slug: soleus
  name: Soleus
  group_slug: calves
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/soleus.svg

- slug: splenius_capitis
  name: Splenius Capitis
  group_slug: spinal_erectors

- slug: splenius_cervicis
  name: Splenius Cervicis
  group_slug: spinal_erectors

- slug: sternocleidomastoid
  name: Sternocleidomastoid
  group_slug: shoulders
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/sternocleidomastoid.svg

- slug: supinator
  name: Supinator
  group_slug: forearms

- slug: tensor_fasciae_latae
  name: Tensor Fasciae Latae
  group_slug: abductors
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/tensor_fasciae_latae.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/tensor_fasciae_latae.svg

- slug: teres_major
  name: Teres Major
  group_slug: shoulders
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/teres_major.svg

- slug: tibialis_anterior
  name: Tibialis Anterior
  group_slug: calves

- slug: tibialis_posterior
  name: Tibialis Posterior
  group_slug: calves

- slug: thoracolumbar_fascia_posterior_layer
  name: Thoracolumbar Fascia (Posterior Layer)
  group_slug: spinal_erectors
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/thoracolumbar_fascia_posterior_layer.svg

- slug: transversus_abdominis
  name: Transversus Abdominis
  group_slug: abs

- slug: trapezius
  name: Trapezius
  group_slug: upper_back
  overlays:
    - view: front
      variant: "upper"
      path: svgs/front/muscles/trapezius_upper.svg
    - view: rear
      variant: "lower"
      path: svgs/rear/muscles/trapezius_lower.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/trapezius.svg

- slug: triceps_brachii
  name: Triceps Brachii
  group_slug: triceps

- slug: triceps_brachii_lateral
  name: Triceps Brachii (Lateral Head)
  group_slug: triceps
  overlays:
    - view: rear
      variant: null
      path: svgs/rear/muscles/triceps_brachii_lateral.svg

- slug: triceps_brachii_long
  name: Triceps Brachii (Long Head)
  group_slug: triceps
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/triceps_brachii_long.svg
    - view: rear
      variant: null
      path: svgs/rear/muscles/triceps_brachii_long.svg

- slug: triceps_brachii_medial
  name: Triceps Brachii (Medial Head)
  group_slug: triceps
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/triceps_brachii_medial.svg

- slug: vastus_intermedius
  name: Vastus Intermedius
  group_slug: quads

- slug: vastus_lateralis
  name: Vastus Lateralis
  group_slug: quads
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/vastus_lateralis.svg

- slug: vastus_medialis
  name: Vastus Medialis
  group_slug: quads
  overlays:
    - view: front
      variant: null
      path: svgs/front/muscles/vastus_medialis.svg
