muscles:
  entries:
  - slug: abductor_digiti_minimi
    name: Abductor Digiti Minimi
    group_slug: calves
    region_slug: foot
  - slug: abductor_hallucis
    name: Abductor Hallucis
    group_slug: calves
    region_slug: foot
  - slug: abductor_pollicis_brevis
    name: Abductor Pollicis Brevis
    group_slug: grip
    region_slug: hand
  - slug: abductor_pollicis_longus
    name: Abductor Pollicis Longus
    group_slug: forearms
    region_slug: forearm
  - slug: adductor_brevis
    name: Adductor Brevis
    group_slug: adductors
    region_slug: thigh
  - slug: adductor_group
    name: Hip Adductor Functional Group
    group_slug: adductors
    region_slug: hip
  - slug: adductor_longus
    name: Adductor Longus
    group_slug: adductors
    region_slug: thigh
  - slug: adductor_magnus
    name: Adductor Magnus
    group_slug: adductors
    region_slug: thigh
  - slug: adductor_pollicis
    name: Adductor Pollicis
    group_slug: grip
    region_slug: hand
  - slug: anconeus
    name: Anconeus
    group_slug: triceps
    region_slug: upper_arm
  - slug: biceps_brachii
    name: Biceps Brachii
    group_slug: biceps
    region_slug: upper_arm
  - slug: biceps_femoris
    name: Biceps Femoris
    group_slug: hamstrings
    region_slug: posterior_thigh
  - slug: brachialis
    name: Brachialis
    group_slug: biceps
    region_slug: upper_arm
  - slug: brachioradialis
    name: Brachioradialis
    group_slug: forearms
    region_slug: forearm
  - slug: coccygeus
    name: Coccygeus
    group_slug: pelvic_floor
    region_slug: pelvis
  - slug: coracobrachialis
    name: Coracobrachialis
    group_slug: biceps
    region_slug: upper_arm
  - slug: deep_transverse_perineal
    name: Deep Transverse Perineal
    group_slug: pelvic_floor
    region_slug: pelvis
  - slug: deltoid
    name: Deltoid
    group_slug: shoulders
    region_slug: shoulder
  - slug: anterior_deltoids
    name: Anterior Deltoids
    group_slug: shoulders
    region_slug: shoulder
  - slug: lateral_deltoids
    name: Lateral Deltoids
    group_slug: shoulders
    region_slug: shoulder
  - slug: medial_deltoids
    name: Medial Deltoids
    group_slug: shoulders
    region_slug: shoulder
  - slug: posterior_deltoids
    name: Posterior Deltoids
    group_slug: shoulders
    region_slug: shoulder
  - slug: infraspinatus
    name: Infraspinatus
    group_slug: shoulders
    region_slug: shoulder
  - slug: subscapularis
    name: Subscapularis
    group_slug: shoulders
    region_slug: shoulder
  - slug: supraspinatus
    name: Supraspinatus
    group_slug: shoulders
    region_slug: shoulder
  - slug: teres_minor
    name: Teres Minor
    group_slug: shoulders
    region_slug: shoulder
  - slug: diaphragm
    name: Diaphragm
    group_slug: respiratory
    region_slug: thorax
  - slug: digastric
    name: Digastric
    group_slug: neck
    region_slug: suprahyoid
  - slug: dorsal_interosseous_1
    name: First Dorsal Interosseous
    group_slug: grip
    region_slug: hand
  - slug: dorsal_interosseous_2
    name: Second Dorsal Interosseous
    group_slug: grip
    region_slug: hand
  - slug: dorsal_interosseous_3
    name: Third Dorsal Interosseous
    group_slug: grip
    region_slug: hand
  - slug: dorsal_interosseous_4
    name: Fourth Dorsal Interosseous
    group_slug: grip
    region_slug: hand
  - slug: dorsiflexor_group
    name: Dorsiflexor Functional Group
    group_slug: calves
    region_slug: leg
  - slug: erector_spinae_iliocostalis
    name: Iliocostalis
    group_slug: lower_back
    region_slug: back
  - slug: erector_spinae_longissimus
    name: Longissimus
    group_slug: lower_back
    region_slug: back
  - slug: erector_spinae_spinalis
    name: Spinalis
    group_slug: lower_back
    region_slug: back
  - slug: erector_spinae
    name: Erector Spinae (Group)
    group_slug: lower_back
    region_slug: back
  - slug: extensor_carpi_radialis_brevis
    name: Extensor Carpi Radialis Brevis
    group_slug: forearms
    region_slug: forearm
  - slug: extensor_carpi_radialis_longus
    name: Extensor Carpi Radialis Longus
    group_slug: forearms
    region_slug: forearm
  - slug: extensor_carpi_ulnaris
    name: Extensor Carpi Ulnaris
    group_slug: forearms
    region_slug: forearm
  - slug: extensor_digiti_minimi
    name: Extensor Digiti Minimi
    group_slug: forearms
    region_slug: forearm
  - slug: extensor_digitorum
    name: Extensor Digitorum
    group_slug: forearms
    region_slug: forearm
  - slug: extensor_digitorum_longus
    name: Extensor Digitorum Longus
    group_slug: calves
    region_slug: leg
  - slug: extensor_hallucis_longus
    name: Extensor Hallucis Longus
    group_slug: calves
    region_slug: leg
  - slug: extensor_indicis
    name: Extensor Indicis
    group_slug: forearms
    region_slug: forearm
  - slug: extensor_pollicis_brevis
    name: Extensor Pollicis Brevis
    group_slug: forearms
    region_slug: forearm
  - slug: extensor_pollicis_longus
    name: Extensor Pollicis Longus
    group_slug: forearms
    region_slug: forearm
  - slug: external_intercostals
    name: External Intercostals
    group_slug: respiratory
    region_slug: thorax
  - slug: external_oblique
    name: External Oblique
    group_slug: obliques
    region_slug: abdomen
  - slug: obliques
    name: Obliques (Group)
    group_slug: obliques
    region_slug: abdomen
  - slug: external_urethral_sphincter
    name: External Urethral Sphincter
    group_slug: pelvic_floor
    region_slug: pelvis
  - slug: fibularis_brevis
    name: Fibularis Brevis
    group_slug: calves
    region_slug: leg
  - slug: fibularis_longus
    name: Fibularis Longus
    group_slug: calves
    region_slug: leg
  - slug: flexor_carpi_radialis
    name: Flexor Carpi Radialis
    group_slug: forearms
    region_slug: forearm
  - slug: flexor_carpi_ulnaris
    name: Flexor Carpi Ulnaris
    group_slug: forearms
    region_slug: forearm
  - slug: flexor_digiti_minimi_brevis
    name: Flexor Digiti Minimi Brevis
    group_slug: grip
    region_slug: hand
  - slug: flexor_digitorum_brevis
    name: Flexor Digitorum Brevis
    group_slug: calves
    region_slug: foot
  - slug: flexor_digitorum_longus
    name: Flexor Digitorum Longus
    group_slug: calves
    region_slug: leg
  - slug: flexor_digitorum_profundus
    name: Flexor Digitorum Profundus
    group_slug: forearms
    region_slug: forearm
  - slug: flexor_digitorum_superficialis
    name: Flexor Digitorum Superficialis
    group_slug: forearms
    region_slug: forearm
  - slug: flexor_hallucis_longus
    name: Flexor Hallucis Longus
    group_slug: calves
    region_slug: leg
  - slug: flexor_pollicis_brevis
    name: Flexor Pollicis Brevis
    group_slug: grip
    region_slug: hand
  - slug: flexor_pollicis_longus
    name: Flexor Pollicis Longus
    group_slug: forearms
    region_slug: forearm
  - slug: gastrocnemius
    name: Gastrocnemius
    group_slug: calves
    region_slug: leg
  - slug: geniohyoid
    name: Geniohyoid
    group_slug: neck
    region_slug: suprahyoid
  - slug: gluteus_maximus
    name: Gluteus Maximus
    group_slug: glutes
    region_slug: hip
  - slug: gluteus_medius
    name: Gluteus Medius
    group_slug: glutes
    region_slug: hip
  - slug: gluteus_minimus
    name: Gluteus Minimus
    group_slug: glutes
    region_slug: hip
  - slug: gracilis
    name: Gracilis
    group_slug: adductors
    region_slug: thigh
  - slug: hamstring_group
    name: Hamstring Functional Group
    group_slug: hamstrings
    region_slug: posterior_thigh
  - slug: hip_flexor_group
    name: Hip Flexor Functional Group
    group_slug: hip_flexors
    region_slug: hip
  - slug: iliopsoas
    name: Iliopsoas
    group_slug: hip_flexors
    region_slug: hip
  - slug: hip_medial_rotators
    name: Hip Medial Rotators
    group_slug: glutes
    region_slug: hip
  - slug: iliotibial_band_muscles
    name: Iliotibial Band Muscles (Functional Group)
    group_slug: glutes
    region_slug: hip
  - slug: infrahyoid_group
    name: Infrahyoid Functional Group
    group_slug: neck
    region_slug: infrahyoid
  - slug: innermost_intercostals
    name: Innermost Intercostals
    group_slug: respiratory
    region_slug: thorax
  - slug: internal_intercostals
    name: Internal Intercostals
    group_slug: respiratory
    region_slug: thorax
  - slug: internal_oblique
    name: Internal Oblique
    group_slug: obliques
    region_slug: abdomen
  - slug: transverse_abdominis
    name: Transverse Abdominis
    group_slug: abs
    region_slug: abdomen
  - slug: interossei_dorsal
    name: Dorsal Interossei
    group_slug: grip
    region_slug: hand
  - slug: interossei_palmar
    name: Palmar Interossei
    group_slug: grip
    region_slug: hand
  - slug: latissimus_dorsi
    name: Latissimus Dorsi
    group_slug: lats
    region_slug: shoulder
  - slug: levator_ani
    name: Levator Ani
    group_slug: pelvic_floor
    region_slug: pelvis
  - slug: levator_scapulae
    name: Levator Scapulae
    group_slug: upper_back
    region_slug: back
  - slug: rhomboids
    name: Rhomboids
    group_slug: upper_back
    region_slug: back
  - slug: levatores_costarum
    name: Levatores Costarum
    group_slug: respiratory
    region_slug: thorax
  - slug: lumbrical_1
    name: Lumbrical 1
    group_slug: calves
    region_slug: foot
  - slug: lumbricals_1_2
    name: Lumbricals 1 and 2
    group_slug: grip
    region_slug: hand
  - slug: lumbricals_2_4
    name: Lumbricals 2-4
    group_slug: calves
    region_slug: foot
  - slug: lumbricals_3_4
    name: Lumbricals 3 and 4
    group_slug: grip
    region_slug: hand
  - slug: multifidus
    name: Multifidus
    group_slug: lower_back
    region_slug: back
  - slug: mylohyoid
    name: Mylohyoid
    group_slug: neck
    region_slug: suprahyoid
  - slug: omohyoid
    name: Omohyoid
    group_slug: neck
    region_slug: infrahyoid
  - slug: opponens_digiti_minimi
    name: Opponens Digiti Minimi
    group_slug: grip
    region_slug: hand
  - slug: opponens_pollicis
    name: Opponens Pollicis
    group_slug: grip
    region_slug: hand
  - slug: palmar_interosseous_1
    name: First Palmar Interosseous
    group_slug: grip
    region_slug: hand
  - slug: palmar_interosseous_2
    name: Second Palmar Interosseous
    group_slug: grip
    region_slug: hand
  - slug: palmar_interosseous_3
    name: Third Palmar Interosseous
    group_slug: grip
    region_slug: hand
  - slug: palmaris_brevis
    name: Palmaris Brevis
    group_slug: grip
    region_slug: hand
  - slug: palmaris_longus
    name: Palmaris Longus
    group_slug: forearms
    region_slug: forearm
  - slug: pectineus
    name: Pectineus
    group_slug: adductors
    region_slug: thigh
  - slug: pectoralis_major
    name: Pectoralis Major
    group_slug: chest
    region_slug: shoulder
  - slug: pelvic_floor_group
    name: Pelvic Floor Functional Group
    group_slug: pelvic_floor
    region_slug: pelvis
  - slug: piriformis
    name: Piriformis
    group_slug: glutes
    region_slug: hip
  - slug: plantaris
    name: Plantaris
    group_slug: calves
    region_slug: leg
  - slug: pronator_quadratus
    name: Pronator Quadratus
    group_slug: forearms
    region_slug: forearm
  - slug: pronator_teres
    name: Pronator Teres
    group_slug: forearms
    region_slug: forearm
  - slug: quadratus_plantae
    name: Quadratus Plantae
    group_slug: calves
    region_slug: foot
  - slug: quadriceps_group
    name: Quadriceps Functional Group
    group_slug: quads
    region_slug: thigh
  - slug: rectus_abdominis
    name: Rectus Abdominis
    group_slug: abs
    region_slug: abdomen
  - slug: rectus_femoris
    name: Rectus Femoris
    group_slug: quads
    region_slug: thigh
  - slug: rhomboid_major
    name: Rhomboid Major
    group_slug: upper_back
    region_slug: back
  - slug: rhomboid_minor
    name: Rhomboid Minor
    group_slug: upper_back
    region_slug: back
  - slug: rotator_cuff
    name: Rotator Cuff Group
    group_slug: shoulders
    region_slug: shoulder
  - slug: sartorius
    name: Sartorius
    group_slug: hip_flexors
    region_slug: thigh
  - slug: semimembranosus
    name: Semimembranosus
    group_slug: hamstrings
    region_slug: posterior_thigh
  - slug: semispinalis_capitis
    name: Semispinalis Capitis
    group_slug: lower_back
    region_slug: back
  - slug: semispinalis_cervicis
    name: Semispinalis Cervicis
    group_slug: lower_back
    region_slug: back
  - slug: semitendinosus
    name: Semitendinosus
    group_slug: hamstrings
    region_slug: posterior_thigh
  - slug: serratus_anterior
    name: Serratus Anterior
    group_slug: shoulders
    region_slug: thorax
  - slug: serratus_posterior_inferior
    name: Serratus Posterior Inferior
    group_slug: respiratory
    region_slug: thorax
  - slug: serratus_posterior_inferior_back
    name: Serratus Posterior Inferior
    group_slug: respiratory
    region_slug: back
  - slug: serratus_posterior_superior
    name: Serratus Posterior Superior
    group_slug: respiratory
    region_slug: thorax
  - slug: serratus_posterior_superior_back
    name: Serratus Posterior Superior
    group_slug: respiratory
    region_slug: back
  - slug: soleus
    name: Soleus
    group_slug: calves
    region_slug: leg
  - slug: splenius_capitis
    name: Splenius Capitis
    group_slug: neck
    region_slug: back
  - slug: splenius_cervicis
    name: Splenius Cervicis
    group_slug: neck
    region_slug: back
  - slug: sternocleidomastoid
    name: Sternocleidomastoid
    group_slug: neck
    region_slug: neck
  - slug: sternohyoid
    name: Sternohyoid
    group_slug: neck
    region_slug: infrahyoid
  - slug: sternothyroid
    name: Sternothyroid
    group_slug: neck
    region_slug: infrahyoid
  - slug: stylohyoid
    name: Stylohyoid
    group_slug: neck
    region_slug: suprahyoid
  - slug: subcostals
    name: Subcostals
    group_slug: respiratory
    region_slug: thorax
  - slug: supinator
    name: Supinator
    group_slug: forearms
    region_slug: forearm
  - slug: suprahyoid_group
    name: Suprahyoid Functional Group
    group_slug: neck
    region_slug: suprahyoid
  - slug: tensor_fasciae_latae
    name: Tensor Fasciae Latae
    group_slug: glutes
    region_slug: hip
  - slug: teres_major
    name: Teres Major
    group_slug: shoulders
    region_slug: shoulder
  - slug: thyrohyoid
    name: Thyrohyoid
    group_slug: neck
    region_slug: infrahyoid
  - slug: tibialis_anterior
    name: Tibialis Anterior
    group_slug: calves
    region_slug: leg
  - slug: tibialis_posterior
    name: Tibialis Posterior
    group_slug: calves
    region_slug: leg
  - slug: transversus_abdominis
    name: Transversus Abdominis
    group_slug: obliques
    region_slug: abdomen
  - slug: transversus_thoracis
    name: Transversus Thoracis
    group_slug: respiratory
    region_slug: thorax
  - slug: trapezius
    name: Trapezius
    group_slug: upper_back
    region_slug: back
  - slug: upper_trapezius
    name: Upper Trapezius
    group_slug: upper_back
    region_slug: neck
  - slug: triceps_brachii
    name: Triceps Brachii
    group_slug: triceps
    region_slug: upper_arm
  - slug: vastus_intermedius
    name: Vastus Intermedius
    group_slug: quads
    region_slug: thigh
  - slug: vastus_lateralis
    name: Vastus Lateralis
    group_slug: quads
    region_slug: thigh
  - slug: vastus_medialis
    name: Vastus Medialis
    group_slug: quads
    region_slug: thigh
  - slug: quadriceps_femoris
    name: Quadriceps Femoris
    group_slug: quads
    region_slug: thigh
