muscle_regions:
  entries:
  - slug: abdomen
    name: Abdomen
  - slug: back
    name: Back
  - slug: foot
    name: Foot
  - slug: forearm
    name: Forearm
  - slug: hand
    name: Hand
  - slug: hip
    name: Hip
  - slug: infrahyoid
    name: Infrahyoid
  - slug: leg
    name: Leg
  - slug: neck
    name: Neck
  - slug: pelvis
    name: Pelvis
  - slug: posterior_thigh
    name: Posterior Thigh
  - slug: shoulder
    name: Shoulder
  - slug: suprahyoid
    name: Suprahyoid
  - slug: thigh
    name: Thigh
  - slug: thorax
    name: Thorax
  - slug: upper_arm
    name: Upper Arm
