muscles:
- alias: adductor_magnus
  name: Adductor Magnus
  targets:
  - id: adductor_magnus
    label: Muscle
- alias: anconeus
  name: Anconeus
  targets:
  - id: anconeus
    label: Muscle
- alias: anterior_deltoids
  name: Anterior Deltoids
  targets:
  - id: deltoid_anterior
    label: MuscleHead
- alias: biceps_brachii
  name: Biceps Brachii
  targets:
  - id: biceps_brachii
    label: Muscle
- alias: biceps_femoris
  name: Biceps Femoris
  targets:
  - id: biceps_femoris
    label: Muscle
- alias: brachialis
  name: Brachialis
  targets:
  - id: brachialis
    label: Muscle
- alias: brachioradialis
  name: Brachioradialis
  targets:
  - id: brachioradialis
    label: Muscle
- alias: erector_spinae
  name: Erector Spinae
  targets:
  - id: erector_spinae_spinalis
    label: Muscle
  - id: erector_spinae_longissimus
    label: Muscle
  - id: erector_spinae_iliocostalis
    label: Muscle
- alias: extensor_digitorum_longus
  name: Extensor Digitorum Longus
  targets:
  - id: extensor_digitorum_longus
    label: Muscle
- alias: extensor_hallucis_longus
  name: Extensor Hallucis Longus
  targets:
  - id: extensor_hallucis_longus
    label: Muscle
- alias: flexor_carpi_radialis
  name: Flexor Carpi Radialis
  targets:
  - id: flexor_carpi_radialis
    label: Muscle
- alias: gastrocnemius
  name: Gastrocnemius
  targets:
  - id: gastrocnemius
    label: Muscle
- alias: gluteus_maximus
  name: Gluteus Maximus
  targets:
  - id: gluteus_maximus
    label: Muscle
- alias: gluteus_medius
  name: Gluteus Medius
  targets:
  - id: gluteus_medius
    label: Muscle
- alias: gluteus_minimus
  name: Gluteus Minimus
  targets:
  - id: gluteus_minimus
    label: Muscle
- alias: iliopsoas
  name: Iliopsoas
  targets:
  - id: hip_flexor_group
    label: Muscle
- alias: infraspinatus
  name: Infraspinatus
  targets:
  - id: infraspinatus
    label: MuscleHead
- alias: lateral_deltoids
  name: Lateral Deltoids
  targets:
  - id: deltoid_middle
    label: MuscleHead
- alias: latissimus_dorsi
  name: Latissimus Dorsi
  targets:
  - id: latissimus_dorsi
    label: Muscle
- alias: levator_scapulae
  name: Levator Scapulae
  targets:
  - id: levator_scapulae
    label: Muscle
- alias: medial_deltoids
  name: Medial Deltoids
  targets:
  - id: deltoid_middle
    label: MuscleHead
- alias: obliques
  name: Obliques
  targets:
  - id: external_oblique
    label: Muscle
  - id: internal_oblique
    label: Muscle
- alias: pectoralis_major
  name: Pectoralis Major
  targets:
  - id: pectoralis_major
    label: Muscle
- alias: posterior_deltoids
  name: Posterior Deltoids
  targets:
  - id: deltoid_posterior
    label: MuscleHead
- alias: quadriceps_femoris
  name: Quadriceps Femoris
  targets:
  - id: rectus_femoris
    label: Muscle
  - id: vastus_lateralis
    label: Muscle
  - id: vastus_medialis
    label: Muscle
  - id: vastus_intermedius
    label: Muscle
- alias: rectus_abdominis
  name: Rectus Abdominis
  targets:
  - id: rectus_abdominis
    label: Muscle
- alias: rectus_femoris
  name: Rectus Femoris
  targets:
  - id: rectus_femoris
    label: Muscle
- alias: rhomboids
  name: Rhomboids
  targets:
  - id: rhomboid_major
    label: Muscle
  - id: rhomboid_minor
    label: Muscle
- alias: serratus_anterior
  name: Serratus Anterior
  targets:
  - id: serratus_anterior
    label: Muscle
- alias: soleus
  name: Soleus
  targets:
  - id: soleus
    label: Muscle
- alias: subscapularis
  name: Subscapularis
  targets:
  - id: subscapularis
    label: MuscleHead
- alias: supraspinatus
  name: Supraspinatus
  targets:
  - id: supraspinatus
    label: MuscleHead
- alias: tensor_fasciae_latae
  name: Tensor Fasciae Latae
  targets:
  - id: tensor_fasciae_latae
    label: Muscle
- alias: teres_major
  name: Teres Major
  targets:
  - id: teres_major
    label: Muscle
- alias: teres_minor
  name: Teres Minor
  targets:
  - id: teres_minor
    label: MuscleHead
- alias: tibialis_anterior
  name: Tibialis Anterior
  targets:
  - id: tibialis_anterior
    label: Muscle
- alias: tibialis_posterior
  name: Tibialis Posterior
  targets:
  - id: tibialis_posterior
    label: Muscle
- alias: transverse_abdominis
  name: Transverse Abdominis
  targets:
  - id: transversus_abdominis
    label: Muscle
- alias: trapezius
  name: Trapezius
  targets:
  - id: trapezius
    label: Muscle
- alias: triceps_brachii
  name: Triceps Brachii
  targets:
  - id: triceps_brachii
    label: Muscle
- alias: upper_trapezius
  name: Upper Trapezius
  targets:
  - id: trapezius
    label: Muscle
- alias: vastus_mediais
  name: Vastus Mediais
  targets:
  - id: vastus_medialis
    label: Muscle
