actions:
- id: scapula_elevation
  name: Scapula Elevation
  joint: scapulothoracic
  type: elevation
  primary_movers:
  - trapezius
  - levator_scapulae
- id: scapula_depression
  name: Scapula Depression
  joint: scapulothoracic
  type: depression
  primary_movers:
  - trapezius
  - latissimus_dorsi_head
  - serratus_posterior_inferior_back
- id: scapula_retraction
  name: Scapula Retraction
  joint: scapulothoracic
  type: retraction
  primary_movers:
  - trapezius
  - rhomboid_major
  - rhomboid_minor
- id: scapula_downward_rotation
  name: Scapula Downward Rotation
  joint: scapulothoracic
  type: rotation
  primary_movers:
  - levator_scapulae
  - rhomboid_major
  - rhomboid_minor
- id: scapula_upward_rotation
  name: Scapula Upward Rotation
  joint: scapulothoracic
  type: rotation
  primary_movers:
  - trapezius
- id: spinal_extension
  name: Spinal Extension
  joint: vertebral_column
  type: extension
  primary_movers:
  - erector_spinae_spinalis
  - erector_spinae_longissimus
  - erector_spinae_iliocostalis
  - multifidus
  - semispinalis_capitis
  - semispinalis_cervicis
- id: spinal_lateral_flexion
  name: Spinal Lateral Flexion
  joint: vertebral_column
  type: lateral_flexion
  primary_movers:
  - erector_spinae_longissimus
  - erector_spinae_iliocostalis
  - splenius_capitis
  - splenius_cervicis
- id: spinal_rotation
  name: Spinal Rotation
  joint: vertebral_column
  type: rotation
  primary_movers:
  - multifidus
  - semispinalis_cervicis
  - splenius_cervicis
- id: cervical_extension
  name: Cervical Extension
  joint: cervical_spine
  type: extension
  primary_movers:
  - semispinalis_capitis
  - semispinalis_cervicis
  - splenius_capitis
  - splenius_cervicis
  - trapezius
- id: forced_expiration_assist
  name: Forced Expiration Assistance
  joint: thoracic_cage
  type: expiration
  primary_movers:
  - serratus_posterior_inferior_back
