muscles:
- id: trapezius
  name: Trapezius
  group: Superficial Back Muscles
  order: Back
  heads:
  - trapezius_upper_head
  - trapezius_middle_head
  - trapezius_lower_head
  insertion:
  - lateral_clavicle
  - acromion_process
  - spine_of_scapula
  actions:
  - scapula_elevation
  - scapula_retraction
  - scapula_depression
  - scapula_upward_rotation
  antagonists: []
- id: levator_scapulae
  name: Levator Scapulae
  group: Superficial Back Muscles
  order: Back
  heads:
  - levator_scapulae_head
  insertion:
  - medial_border_scapula
  - superior_angle_scapula
  actions:
  - scapula_elevation
  - scapula_downward_rotation
  antagonists: []
- id: rhomboid_minor
  name: Rhomboid Minor
  group: Superficial Back Muscles
  order: Back
  heads:
  - rhomboid_minor_head
  insertion:
  - medial_border_scapula
  actions:
  - scapula_retraction
  - scapula_downward_rotation
  antagonists: []
- id: rhomboid_major
  name: Rhomboid Major
  group: Superficial Back Muscles
  order: Back
  heads:
  - rhomboid_major_head
  insertion:
  - medial_border_scapula
  - inferior_angle_scapula
  actions:
  - scapula_retraction
  - scapula_downward_rotation
  antagonists: []
- id: serratus_posterior_inferior_back
  name: Serratus Posterior Inferior
  group: Intermediate Back Muscles
  order: Back
  heads:
  - serratus_posterior_inferior_back_head
  insertion:
  - ribs_9_12
  actions:
  - forced_expiration_assist
  antagonists: []
- id: erector_spinae_spinalis
  name: Spinalis
  group: Erector Spinae
  order: Back
  heads:
  - erector_spinae_spinalis
  insertion:
  - spinous_processes_C1_C2
  - spinous_processes_C3_T12
  actions:
  - spinal_extension
  antagonists: []
- id: erector_spinae_longissimus
  name: Longissimus
  group: Erector Spinae
  order: Back
  heads:
  - erector_spinae_longissimus
  insertion:
  - transverse_processes_C1_C4
  - transverse_processes_T1_T12
  - ribs_3_6
  actions:
  - spinal_extension
  - spinal_lateral_flexion
  antagonists: []
- id: erector_spinae_iliocostalis
  name: Iliocostalis
  group: Erector Spinae
  order: Back
  heads:
  - erector_spinae_iliocostalis
  insertion:
  - ribs_3_6
  - ribs_6_12
  - transverse_processes_C1_C4
  actions:
  - spinal_extension
  - spinal_lateral_flexion
  antagonists: []
- id: multifidus
  name: Multifidus
  group: Transversospinales
  order: Back
  heads:
  - multifidus_head
  insertion:
  - spinous_processes_C3_T12
  - spinous_processes_T7_L5
  actions:
  - spinal_extension
  - spinal_rotation
  antagonists: []
- id: semispinalis_capitis
  name: Semispinalis Capitis
  group: Transversospinales
  order: Back
  heads:
  - semispinalis_capitis_head
  insertion:
  - superior_nuchal_line
  - external_occipital_protuberance
  actions:
  - cervical_extension
  - spinal_rotation
  antagonists: []
- id: semispinalis_cervicis
  name: Semispinalis Cervicis
  group: Transversospinales
  order: Back
  heads:
  - semispinalis_cervicis_head
  insertion:
  - spinous_processes_C1_C2
  - spinous_processes_C3_T12
  actions:
  - cervical_extension
  - spinal_rotation
  antagonists: []
- id: splenius_capitis
  name: Splenius Capitis
  group: Superficial Intrinsic Muscles
  order: Back
  heads:
  - splenius_capitis_head
  insertion:
  - mastoid_process
  - superior_nuchal_line
  actions:
  - cervical_extension
  - spinal_lateral_flexion
  - spinal_rotation
  antagonists: []
- id: splenius_cervicis
  name: Splenius Cervicis
  group: Superficial Intrinsic Muscles
  order: Back
  heads:
  - splenius_cervicis_head
  insertion:
  - transverse_processes_C1_C4
  actions:
  - cervical_extension
  - spinal_lateral_flexion
  - spinal_rotation
  antagonists: []
